//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advanced_CSharp_Project_3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/connectToDB", ReplyAction="*")]
        bool connectToDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/connectToDB", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> connectToDBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/disconnectFromDB", ReplyAction="*")]
        void disconnectFromDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/disconnectFromDB", ReplyAction="*")]
        System.Threading.Tasks.Task disconnectFromDBAsync();
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkIfUserExist", ReplyAction="*")]
        Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistResponse checkIfUserExist(Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkIfUserExist", ReplyAction="*")]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistResponse> checkIfUserExistAsync(Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        Advanced_CSharp_Project_3.ServiceReference1.addUserResponse addUser(Advanced_CSharp_Project_3.ServiceReference1.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.addUserResponse> addUserAsync(Advanced_CSharp_Project_3.ServiceReference1.addUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/removeUser", ReplyAction="*")]
        Advanced_CSharp_Project_3.ServiceReference1.removeUserResponse removeUser(Advanced_CSharp_Project_3.ServiceReference1.removeUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/removeUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.removeUserResponse> removeUserAsync(Advanced_CSharp_Project_3.ServiceReference1.removeUserRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateUserWithSecurity", ReplyAction="*")]
        Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityResponse validateUserWithSecurity(Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateUserWithSecurity", ReplyAction="*")]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityResponse> validateUserWithSecurityAsync(Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateUser", ReplyAction="*")]
        Advanced_CSharp_Project_3.ServiceReference1.validateUserResponse validateUser(Advanced_CSharp_Project_3.ServiceReference1.validateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.validateUserResponse> validateUserAsync(Advanced_CSharp_Project_3.ServiceReference1.validateUserRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/resetPassword", ReplyAction="*")]
        Advanced_CSharp_Project_3.ServiceReference1.resetPasswordResponse resetPassword(Advanced_CSharp_Project_3.ServiceReference1.resetPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/resetPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.resetPasswordResponse> resetPasswordAsync(Advanced_CSharp_Project_3.ServiceReference1.resetPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name recipeName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addRecipe", ReplyAction="*")]
        Advanced_CSharp_Project_3.ServiceReference1.addRecipeResponse addRecipe(Advanced_CSharp_Project_3.ServiceReference1.addRecipeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addRecipe", ReplyAction="*")]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.addRecipeResponse> addRecipeAsync(Advanced_CSharp_Project_3.ServiceReference1.addRecipeRequest request);
        
        // CODEGEN: Generating message contract since element name recipeNum from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rateRecipe", ReplyAction="*")]
        Advanced_CSharp_Project_3.ServiceReference1.rateRecipeResponse rateRecipe(Advanced_CSharp_Project_3.ServiceReference1.rateRecipeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rateRecipe", ReplyAction="*")]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.rateRecipeResponse> rateRecipeAsync(Advanced_CSharp_Project_3.ServiceReference1.rateRecipeRequest request);
        
        // CODEGEN: Generating message contract since element name recipeNum from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRecipeTitle", ReplyAction="*")]
        Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleResponse getRecipeTitle(Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRecipeTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleResponse> getRecipeTitleAsync(Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleRequest request);
        
        // CODEGEN: Generating message contract since element name recipeNum from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRecipeIngredients", ReplyAction="*")]
        Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsResponse getRecipeIngredients(Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRecipeIngredients", ReplyAction="*")]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsResponse> getRecipeIngredientsAsync(Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsRequest request);
        
        // CODEGEN: Generating message contract since element name recipeNum from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRecipeMethod", ReplyAction="*")]
        Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodResponse getRecipeMethod(Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRecipeMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodResponse> getRecipeMethodAsync(Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodRequest request);
        
        // CODEGEN: Generating message contract since element name recipeName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/removeRecipe", ReplyAction="*")]
        Advanced_CSharp_Project_3.ServiceReference1.removeRecipeResponse removeRecipe(Advanced_CSharp_Project_3.ServiceReference1.removeRecipeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/removeRecipe", ReplyAction="*")]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.removeRecipeResponse> removeRecipeAsync(Advanced_CSharp_Project_3.ServiceReference1.removeRecipeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkIfUserExistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkIfUserExist", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistRequestBody Body;
        
        public checkIfUserExistRequest() {
        }
        
        public checkIfUserExistRequest(Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkIfUserExistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public checkIfUserExistRequestBody() {
        }
        
        public checkIfUserExistRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkIfUserExistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkIfUserExistResponse", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistResponseBody Body;
        
        public checkIfUserExistResponse() {
        }
        
        public checkIfUserExistResponse(Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkIfUserExistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool checkIfUserExistResult;
        
        public checkIfUserExistResponseBody() {
        }
        
        public checkIfUserExistResponseBody(bool checkIfUserExistResult) {
            this.checkIfUserExistResult = checkIfUserExistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUser", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.addUserRequestBody Body;
        
        public addUserRequest() {
        }
        
        public addUserRequest(Advanced_CSharp_Project_3.ServiceReference1.addUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string security;
        
        public addUserRequestBody() {
        }
        
        public addUserRequestBody(string email, string username, string password, string security) {
            this.email = email;
            this.username = username;
            this.password = password;
            this.security = security;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.addUserResponseBody Body;
        
        public addUserResponse() {
        }
        
        public addUserResponse(Advanced_CSharp_Project_3.ServiceReference1.addUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addUserResult;
        
        public addUserResponseBody() {
        }
        
        public addUserResponseBody(bool addUserResult) {
            this.addUserResult = addUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeUser", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.removeUserRequestBody Body;
        
        public removeUserRequest() {
        }
        
        public removeUserRequest(Advanced_CSharp_Project_3.ServiceReference1.removeUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class removeUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public removeUserRequestBody() {
        }
        
        public removeUserRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.removeUserResponseBody Body;
        
        public removeUserResponse() {
        }
        
        public removeUserResponse(Advanced_CSharp_Project_3.ServiceReference1.removeUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class removeUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool removeUserResult;
        
        public removeUserResponseBody() {
        }
        
        public removeUserResponseBody(bool removeUserResult) {
            this.removeUserResult = removeUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUserWithSecurityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUserWithSecurity", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityRequestBody Body;
        
        public validateUserWithSecurityRequest() {
        }
        
        public validateUserWithSecurityRequest(Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validateUserWithSecurityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string security;
        
        public validateUserWithSecurityRequestBody() {
        }
        
        public validateUserWithSecurityRequestBody(string email, string security) {
            this.email = email;
            this.security = security;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUserWithSecurityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUserWithSecurityResponse", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityResponseBody Body;
        
        public validateUserWithSecurityResponse() {
        }
        
        public validateUserWithSecurityResponse(Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validateUserWithSecurityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool validateUserWithSecurityResult;
        
        public validateUserWithSecurityResponseBody() {
        }
        
        public validateUserWithSecurityResponseBody(bool validateUserWithSecurityResult) {
            this.validateUserWithSecurityResult = validateUserWithSecurityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUser", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.validateUserRequestBody Body;
        
        public validateUserRequest() {
        }
        
        public validateUserRequest(Advanced_CSharp_Project_3.ServiceReference1.validateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public validateUserRequestBody() {
        }
        
        public validateUserRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.validateUserResponseBody Body;
        
        public validateUserResponse() {
        }
        
        public validateUserResponse(Advanced_CSharp_Project_3.ServiceReference1.validateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool validateUserResult;
        
        public validateUserResponseBody() {
        }
        
        public validateUserResponseBody(bool validateUserResult) {
            this.validateUserResult = validateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resetPassword", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.resetPasswordRequestBody Body;
        
        public resetPasswordRequest() {
        }
        
        public resetPasswordRequest(Advanced_CSharp_Project_3.ServiceReference1.resetPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class resetPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string securityQuestion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public resetPasswordRequestBody() {
        }
        
        public resetPasswordRequestBody(string email, string securityQuestion, string password) {
            this.email = email;
            this.securityQuestion = securityQuestion;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resetPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.resetPasswordResponseBody Body;
        
        public resetPasswordResponse() {
        }
        
        public resetPasswordResponse(Advanced_CSharp_Project_3.ServiceReference1.resetPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class resetPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool resetPasswordResult;
        
        public resetPasswordResponseBody() {
        }
        
        public resetPasswordResponseBody(bool resetPasswordResult) {
            this.resetPasswordResult = resetPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRecipeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addRecipe", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.addRecipeRequestBody Body;
        
        public addRecipeRequest() {
        }
        
        public addRecipeRequest(Advanced_CSharp_Project_3.ServiceReference1.addRecipeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addRecipeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recipeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string recipeOwner;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string recipeIngredients;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string recipeMethod;
        
        public addRecipeRequestBody() {
        }
        
        public addRecipeRequestBody(string recipeName, string recipeOwner, string recipeIngredients, string recipeMethod) {
            this.recipeName = recipeName;
            this.recipeOwner = recipeOwner;
            this.recipeIngredients = recipeIngredients;
            this.recipeMethod = recipeMethod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRecipeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addRecipeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.addRecipeResponseBody Body;
        
        public addRecipeResponse() {
        }
        
        public addRecipeResponse(Advanced_CSharp_Project_3.ServiceReference1.addRecipeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addRecipeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addRecipeResult;
        
        public addRecipeResponseBody() {
        }
        
        public addRecipeResponseBody(bool addRecipeResult) {
            this.addRecipeResult = addRecipeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rateRecipeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rateRecipe", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.rateRecipeRequestBody Body;
        
        public rateRecipeRequest() {
        }
        
        public rateRecipeRequest(Advanced_CSharp_Project_3.ServiceReference1.rateRecipeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class rateRecipeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recipeNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int value;
        
        public rateRecipeRequestBody() {
        }
        
        public rateRecipeRequestBody(string recipeNum, int value) {
            this.recipeNum = recipeNum;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rateRecipeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rateRecipeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.rateRecipeResponseBody Body;
        
        public rateRecipeResponse() {
        }
        
        public rateRecipeResponse(Advanced_CSharp_Project_3.ServiceReference1.rateRecipeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class rateRecipeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool rateRecipeResult;
        
        public rateRecipeResponseBody() {
        }
        
        public rateRecipeResponseBody(bool rateRecipeResult) {
            this.rateRecipeResult = rateRecipeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipeTitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipeTitle", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleRequestBody Body;
        
        public getRecipeTitleRequest() {
        }
        
        public getRecipeTitleRequest(Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRecipeTitleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recipeNum;
        
        public getRecipeTitleRequestBody() {
        }
        
        public getRecipeTitleRequestBody(string recipeNum) {
            this.recipeNum = recipeNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipeTitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipeTitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleResponseBody Body;
        
        public getRecipeTitleResponse() {
        }
        
        public getRecipeTitleResponse(Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRecipeTitleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRecipeTitleResult;
        
        public getRecipeTitleResponseBody() {
        }
        
        public getRecipeTitleResponseBody(string getRecipeTitleResult) {
            this.getRecipeTitleResult = getRecipeTitleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipeIngredientsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipeIngredients", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsRequestBody Body;
        
        public getRecipeIngredientsRequest() {
        }
        
        public getRecipeIngredientsRequest(Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRecipeIngredientsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recipeNum;
        
        public getRecipeIngredientsRequestBody() {
        }
        
        public getRecipeIngredientsRequestBody(string recipeNum) {
            this.recipeNum = recipeNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipeIngredientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipeIngredientsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsResponseBody Body;
        
        public getRecipeIngredientsResponse() {
        }
        
        public getRecipeIngredientsResponse(Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRecipeIngredientsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRecipeIngredientsResult;
        
        public getRecipeIngredientsResponseBody() {
        }
        
        public getRecipeIngredientsResponseBody(string getRecipeIngredientsResult) {
            this.getRecipeIngredientsResult = getRecipeIngredientsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipeMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipeMethod", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodRequestBody Body;
        
        public getRecipeMethodRequest() {
        }
        
        public getRecipeMethodRequest(Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRecipeMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recipeNum;
        
        public getRecipeMethodRequestBody() {
        }
        
        public getRecipeMethodRequestBody(string recipeNum) {
            this.recipeNum = recipeNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipeMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipeMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodResponseBody Body;
        
        public getRecipeMethodResponse() {
        }
        
        public getRecipeMethodResponse(Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRecipeMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRecipeMethodResult;
        
        public getRecipeMethodResponseBody() {
        }
        
        public getRecipeMethodResponseBody(string getRecipeMethodResult) {
            this.getRecipeMethodResult = getRecipeMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeRecipeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeRecipe", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.removeRecipeRequestBody Body;
        
        public removeRecipeRequest() {
        }
        
        public removeRecipeRequest(Advanced_CSharp_Project_3.ServiceReference1.removeRecipeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class removeRecipeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recipeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string recipeOwner;
        
        public removeRecipeRequestBody() {
        }
        
        public removeRecipeRequestBody(string recipeName, string recipeOwner) {
            this.recipeName = recipeName;
            this.recipeOwner = recipeOwner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeRecipeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeRecipeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Advanced_CSharp_Project_3.ServiceReference1.removeRecipeResponseBody Body;
        
        public removeRecipeResponse() {
        }
        
        public removeRecipeResponse(Advanced_CSharp_Project_3.ServiceReference1.removeRecipeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class removeRecipeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool removeRecipeResult;
        
        public removeRecipeResponseBody() {
        }
        
        public removeRecipeResponseBody(bool removeRecipeResult) {
            this.removeRecipeResult = removeRecipeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap>, Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool connectToDB() {
            return base.Channel.connectToDB();
        }
        
        public System.Threading.Tasks.Task<bool> connectToDBAsync() {
            return base.Channel.connectToDBAsync();
        }
        
        public void disconnectFromDB() {
            base.Channel.disconnectFromDB();
        }
        
        public System.Threading.Tasks.Task disconnectFromDBAsync() {
            return base.Channel.disconnectFromDBAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistResponse Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.checkIfUserExist(Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistRequest request) {
            return base.Channel.checkIfUserExist(request);
        }
        
        public bool checkIfUserExist(string username) {
            Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistRequestBody();
            inValue.Body.username = username;
            Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistResponse retVal = ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).checkIfUserExist(inValue);
            return retVal.Body.checkIfUserExistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistResponse> Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.checkIfUserExistAsync(Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistRequest request) {
            return base.Channel.checkIfUserExistAsync(request);
        }
        
        public System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistResponse> checkIfUserExistAsync(string username) {
            Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.checkIfUserExistRequestBody();
            inValue.Body.username = username;
            return ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).checkIfUserExistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Advanced_CSharp_Project_3.ServiceReference1.addUserResponse Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.addUser(Advanced_CSharp_Project_3.ServiceReference1.addUserRequest request) {
            return base.Channel.addUser(request);
        }
        
        public bool addUser(string email, string username, string password, string security) {
            Advanced_CSharp_Project_3.ServiceReference1.addUserRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.addUserRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.addUserRequestBody();
            inValue.Body.email = email;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.security = security;
            Advanced_CSharp_Project_3.ServiceReference1.addUserResponse retVal = ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).addUser(inValue);
            return retVal.Body.addUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.addUserResponse> Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.addUserAsync(Advanced_CSharp_Project_3.ServiceReference1.addUserRequest request) {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.addUserResponse> addUserAsync(string email, string username, string password, string security) {
            Advanced_CSharp_Project_3.ServiceReference1.addUserRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.addUserRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.addUserRequestBody();
            inValue.Body.email = email;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.security = security;
            return ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).addUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Advanced_CSharp_Project_3.ServiceReference1.removeUserResponse Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.removeUser(Advanced_CSharp_Project_3.ServiceReference1.removeUserRequest request) {
            return base.Channel.removeUser(request);
        }
        
        public bool removeUser(string username) {
            Advanced_CSharp_Project_3.ServiceReference1.removeUserRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.removeUserRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.removeUserRequestBody();
            inValue.Body.username = username;
            Advanced_CSharp_Project_3.ServiceReference1.removeUserResponse retVal = ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).removeUser(inValue);
            return retVal.Body.removeUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.removeUserResponse> Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.removeUserAsync(Advanced_CSharp_Project_3.ServiceReference1.removeUserRequest request) {
            return base.Channel.removeUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.removeUserResponse> removeUserAsync(string username) {
            Advanced_CSharp_Project_3.ServiceReference1.removeUserRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.removeUserRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.removeUserRequestBody();
            inValue.Body.username = username;
            return ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).removeUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityResponse Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.validateUserWithSecurity(Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityRequest request) {
            return base.Channel.validateUserWithSecurity(request);
        }
        
        public bool validateUserWithSecurity(string email, string security) {
            Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityRequestBody();
            inValue.Body.email = email;
            inValue.Body.security = security;
            Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityResponse retVal = ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).validateUserWithSecurity(inValue);
            return retVal.Body.validateUserWithSecurityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityResponse> Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.validateUserWithSecurityAsync(Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityRequest request) {
            return base.Channel.validateUserWithSecurityAsync(request);
        }
        
        public System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityResponse> validateUserWithSecurityAsync(string email, string security) {
            Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.validateUserWithSecurityRequestBody();
            inValue.Body.email = email;
            inValue.Body.security = security;
            return ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).validateUserWithSecurityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Advanced_CSharp_Project_3.ServiceReference1.validateUserResponse Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.validateUser(Advanced_CSharp_Project_3.ServiceReference1.validateUserRequest request) {
            return base.Channel.validateUser(request);
        }
        
        public bool validateUser(string username, string password) {
            Advanced_CSharp_Project_3.ServiceReference1.validateUserRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.validateUserRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.validateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Advanced_CSharp_Project_3.ServiceReference1.validateUserResponse retVal = ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).validateUser(inValue);
            return retVal.Body.validateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.validateUserResponse> Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.validateUserAsync(Advanced_CSharp_Project_3.ServiceReference1.validateUserRequest request) {
            return base.Channel.validateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.validateUserResponse> validateUserAsync(string username, string password) {
            Advanced_CSharp_Project_3.ServiceReference1.validateUserRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.validateUserRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.validateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).validateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Advanced_CSharp_Project_3.ServiceReference1.resetPasswordResponse Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.resetPassword(Advanced_CSharp_Project_3.ServiceReference1.resetPasswordRequest request) {
            return base.Channel.resetPassword(request);
        }
        
        public bool resetPassword(string email, string securityQuestion, string password) {
            Advanced_CSharp_Project_3.ServiceReference1.resetPasswordRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.resetPasswordRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.resetPasswordRequestBody();
            inValue.Body.email = email;
            inValue.Body.securityQuestion = securityQuestion;
            inValue.Body.password = password;
            Advanced_CSharp_Project_3.ServiceReference1.resetPasswordResponse retVal = ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).resetPassword(inValue);
            return retVal.Body.resetPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.resetPasswordResponse> Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.resetPasswordAsync(Advanced_CSharp_Project_3.ServiceReference1.resetPasswordRequest request) {
            return base.Channel.resetPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.resetPasswordResponse> resetPasswordAsync(string email, string securityQuestion, string password) {
            Advanced_CSharp_Project_3.ServiceReference1.resetPasswordRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.resetPasswordRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.resetPasswordRequestBody();
            inValue.Body.email = email;
            inValue.Body.securityQuestion = securityQuestion;
            inValue.Body.password = password;
            return ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).resetPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Advanced_CSharp_Project_3.ServiceReference1.addRecipeResponse Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.addRecipe(Advanced_CSharp_Project_3.ServiceReference1.addRecipeRequest request) {
            return base.Channel.addRecipe(request);
        }
        
        public bool addRecipe(string recipeName, string recipeOwner, string recipeIngredients, string recipeMethod) {
            Advanced_CSharp_Project_3.ServiceReference1.addRecipeRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.addRecipeRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.addRecipeRequestBody();
            inValue.Body.recipeName = recipeName;
            inValue.Body.recipeOwner = recipeOwner;
            inValue.Body.recipeIngredients = recipeIngredients;
            inValue.Body.recipeMethod = recipeMethod;
            Advanced_CSharp_Project_3.ServiceReference1.addRecipeResponse retVal = ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).addRecipe(inValue);
            return retVal.Body.addRecipeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.addRecipeResponse> Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.addRecipeAsync(Advanced_CSharp_Project_3.ServiceReference1.addRecipeRequest request) {
            return base.Channel.addRecipeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.addRecipeResponse> addRecipeAsync(string recipeName, string recipeOwner, string recipeIngredients, string recipeMethod) {
            Advanced_CSharp_Project_3.ServiceReference1.addRecipeRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.addRecipeRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.addRecipeRequestBody();
            inValue.Body.recipeName = recipeName;
            inValue.Body.recipeOwner = recipeOwner;
            inValue.Body.recipeIngredients = recipeIngredients;
            inValue.Body.recipeMethod = recipeMethod;
            return ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).addRecipeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Advanced_CSharp_Project_3.ServiceReference1.rateRecipeResponse Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.rateRecipe(Advanced_CSharp_Project_3.ServiceReference1.rateRecipeRequest request) {
            return base.Channel.rateRecipe(request);
        }
        
        public bool rateRecipe(string recipeNum, int value) {
            Advanced_CSharp_Project_3.ServiceReference1.rateRecipeRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.rateRecipeRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.rateRecipeRequestBody();
            inValue.Body.recipeNum = recipeNum;
            inValue.Body.value = value;
            Advanced_CSharp_Project_3.ServiceReference1.rateRecipeResponse retVal = ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).rateRecipe(inValue);
            return retVal.Body.rateRecipeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.rateRecipeResponse> Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.rateRecipeAsync(Advanced_CSharp_Project_3.ServiceReference1.rateRecipeRequest request) {
            return base.Channel.rateRecipeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.rateRecipeResponse> rateRecipeAsync(string recipeNum, int value) {
            Advanced_CSharp_Project_3.ServiceReference1.rateRecipeRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.rateRecipeRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.rateRecipeRequestBody();
            inValue.Body.recipeNum = recipeNum;
            inValue.Body.value = value;
            return ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).rateRecipeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleResponse Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.getRecipeTitle(Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleRequest request) {
            return base.Channel.getRecipeTitle(request);
        }
        
        public string getRecipeTitle(string recipeNum) {
            Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleRequestBody();
            inValue.Body.recipeNum = recipeNum;
            Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleResponse retVal = ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).getRecipeTitle(inValue);
            return retVal.Body.getRecipeTitleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleResponse> Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.getRecipeTitleAsync(Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleRequest request) {
            return base.Channel.getRecipeTitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleResponse> getRecipeTitleAsync(string recipeNum) {
            Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.getRecipeTitleRequestBody();
            inValue.Body.recipeNum = recipeNum;
            return ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).getRecipeTitleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsResponse Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.getRecipeIngredients(Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsRequest request) {
            return base.Channel.getRecipeIngredients(request);
        }
        
        public string getRecipeIngredients(string recipeNum) {
            Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsRequestBody();
            inValue.Body.recipeNum = recipeNum;
            Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsResponse retVal = ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).getRecipeIngredients(inValue);
            return retVal.Body.getRecipeIngredientsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsResponse> Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.getRecipeIngredientsAsync(Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsRequest request) {
            return base.Channel.getRecipeIngredientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsResponse> getRecipeIngredientsAsync(string recipeNum) {
            Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.getRecipeIngredientsRequestBody();
            inValue.Body.recipeNum = recipeNum;
            return ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).getRecipeIngredientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodResponse Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.getRecipeMethod(Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodRequest request) {
            return base.Channel.getRecipeMethod(request);
        }
        
        public string getRecipeMethod(string recipeNum) {
            Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodRequestBody();
            inValue.Body.recipeNum = recipeNum;
            Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodResponse retVal = ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).getRecipeMethod(inValue);
            return retVal.Body.getRecipeMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodResponse> Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.getRecipeMethodAsync(Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodRequest request) {
            return base.Channel.getRecipeMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodResponse> getRecipeMethodAsync(string recipeNum) {
            Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.getRecipeMethodRequestBody();
            inValue.Body.recipeNum = recipeNum;
            return ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).getRecipeMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Advanced_CSharp_Project_3.ServiceReference1.removeRecipeResponse Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.removeRecipe(Advanced_CSharp_Project_3.ServiceReference1.removeRecipeRequest request) {
            return base.Channel.removeRecipe(request);
        }
        
        public bool removeRecipe(string recipeName, string recipeOwner) {
            Advanced_CSharp_Project_3.ServiceReference1.removeRecipeRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.removeRecipeRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.removeRecipeRequestBody();
            inValue.Body.recipeName = recipeName;
            inValue.Body.recipeOwner = recipeOwner;
            Advanced_CSharp_Project_3.ServiceReference1.removeRecipeResponse retVal = ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).removeRecipe(inValue);
            return retVal.Body.removeRecipeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.removeRecipeResponse> Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap.removeRecipeAsync(Advanced_CSharp_Project_3.ServiceReference1.removeRecipeRequest request) {
            return base.Channel.removeRecipeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Advanced_CSharp_Project_3.ServiceReference1.removeRecipeResponse> removeRecipeAsync(string recipeName, string recipeOwner) {
            Advanced_CSharp_Project_3.ServiceReference1.removeRecipeRequest inValue = new Advanced_CSharp_Project_3.ServiceReference1.removeRecipeRequest();
            inValue.Body = new Advanced_CSharp_Project_3.ServiceReference1.removeRecipeRequestBody();
            inValue.Body.recipeName = recipeName;
            inValue.Body.recipeOwner = recipeOwner;
            return ((Advanced_CSharp_Project_3.ServiceReference1.WebService1Soap)(this)).removeRecipeAsync(inValue);
        }
    }
}
